"""Migration script generated by Alembic.

Revision ID: ${rev_id}
Revises: ${down_revision}
Create Date: ${create_date}
"""

from alembic import op
import sqlalchemy as sa

def upgrade():
    ${upgrade_ops}

def downgrade():
    ${downgrade_ops}
