from sqlalchemy import Column, Integer, String, Text, DateTime, BigInteger
from core.database import Base

class AssuranceTicket(Base):
    __tablename__ = "assurance_tickets"

    id = Column(BigInteger, primary_key=True, index=True)
    incident = Column(String(100), unique=True, index=True, nullable=False)
    customer = Column(String(100), nullable=True) # Mapping from customer_name
    summary = Column(Text, nullable=True)
    owner_group = Column(String(100), nullable=True)
    owner = Column(String(100), nullable=True)
    external_ticketid = Column(String(100), nullable=True)
    customer_segment = Column(String(100), nullable=True)
    service_no = Column(String(100), nullable=True)
    service_type = Column(String(100), nullable=True)
    reported_date = Column(DateTime, nullable=True)
    lapul = Column(String(100), nullable=True)
    gaul = Column(String(100), nullable=True)
    ttr_customer = Column(String(100), nullable=True)
    ttr_nasional = Column(String(100), nullable=True)
    ttr_regional = Column(String(100), nullable=True)
    ttr_witel = Column(String(100), nullable=True)
    ttr_mitra = Column(String(100), nullable=True)
    ttr_agent = Column(String(100), nullable=True)
    ttr_pending = Column(String(100), nullable=True)
    pending_reason = Column(String(255), nullable=True)
    status = Column(String(100), nullable=True)
    status_date = Column(DateTime, nullable=True)
    resolved_by = Column(String(100), nullable=True)
    workzone = Column(String(100), nullable=True)
    witel = Column(String(100), nullable=True)
    regional = Column(String(100), nullable=True)
    actual_solution = Column(String(255), nullable=True)
    incident_domain = Column(String(255), nullable=True)
    resolved_date = Column(DateTime, nullable=True)
    jumlah_site_tsel_nossa = Column(String(100), nullable=True)
    kategori_site_tsel = Column(String(100), nullable=True)
    impacted_site_tsel = Column(Text, nullable=True)
    divisi = Column(String(100), nullable=True)
    rca = Column(Text, nullable=True)
    evidence = Column(String(255), nullable=True)
    created_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, nullable=True)
    deleted_at = Column(DateTime, nullable=True)
    ttr_end_to_end = Column(String(100), nullable=True)
    cause = Column(Text, nullable=True)
    resolution = Column(Text, nullable=True)
